# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 生活点滴
email: lulongji2011@163.com
description: 生活中我们会经历许许多多的事，不管是好的还是坏的都是为你量身定做的，我希望能用文字的方式来记录这生活的点滴，供以后有所忆。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lulongji3.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  lulongji2
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
